# Generated by Django 4.2.2 on 2023-06-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=18, null=True)),
                ('last_name', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Usertable',
                'verbose_name_plural': 'Usertable',
                'db_table': 't_user',
                'ordering': ['id'],
            },
        ),
    ]
