# Generated by Django 4.2.2 on 2023-06-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0004_deptmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_1.deptmodel'),
        ),
    ]
