# Generated by Django 4.2.2 on 2023-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0005_employeemodel_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='createtime1')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='createtime2')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='idnumber')),
            ],
            options={
                'verbose_name': 'idnumber',
                'verbose_name_plural': 'idnumber',
                'db_table': 't_ID',
                'ordering': ['id'],
            },
        ),
    ]
