# Generated by Django 4.2.2 on 2023-06-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0010_rolemodel_employeemodel_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_list', to='django_1.deptmodel'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='t_Ro', to='django_1.rolemodel'),
        ),
    ]
