# Generated by Django 4.2.2 on 2023-06-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='createtime1')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='createtime2')),
                ('name', models.CharField(max_length=20, verbose_name='name1')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age1')),
                ('wage', models.IntegerField(blank=True, null=True, verbose_name='wage1')),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='phone1')),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='email1')),
            ],
            options={
                'verbose_name': 'Employeetable',
                'verbose_name_plural': 'Employeetable',
                'db_table': 't_rest_Employee',
                'ordering': ['id'],
            },
        ),
    ]
